### ISSUE TITLE
Move from dockerhub to github container registry

### ISSUE THREAD

**Issue by tlalexander** [Twisted-Fields/acorn-precision-farming-rover#22]
I've changed the docker image and tests are now failing. Let's move to github container registry.
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

@merlinran would you have a chance to look at this using the latest Dockerfile?

I suppose my help will be needed at some point to get the image on to the twistedfields github account. If you have time to check it out and advise me on my role that would be rad! Doesn't look too complicated for me to figure out if you are busy. Thanks!!

**Comment by merlinran** [comment]
I was able to push images to GitHub container registry, but the test failed because of https://github.com/Twisted-Fields/acorn-precision-farming-rover/blob/main/vehicle/corner_actuator.py#L30 (among a few other missing dependencies I fixed under `merlin/simulate-robots` branch)
```
from odrive.enums import *
from odrive.utils import _VT100Colors
```

Can you change `main` branch to avoid `corner_actuator.py` depending on them? Maybe hardcode the required enums.

**Comment by merlinran** [comment]
Oh forgot to mention that I managed to install odrive package in the container last week. Hit a tiny problem when abstracting away GPIO but totally solvable. Will find some time to fix this week.

**Comment by tlalexander** [comment]
Interesting, what was the issue? I have not had trouble with that package before.

I have never used github container registry so I need to look at the docs and figure out how to push to it. I will try to look at that soon. I am doing a bunch of fixes to the nav system and once it is fixed I would love to write tests for it.

**Comment by tlalexander** [comment]
Okay I was able to push to ghcr and I have updated the main repo with your action yaml to run tests using the new target container. I also moved from running "make test" to "pytest" and made it work in main.

You can see a successful test run here:
https://github.com/Twisted-Fields/acorn-precision-farming-rover/actions/runs/2038974175

I have also added some new tests. One I am excited about is it actually runs the robot on a path in simulation and confirms the robot makes it to one end of the path and then back to the other end. If navigation breaks this test will fail!
