### ISSUE TITLE
Temporary failure resolving ubuntu 

### ISSUE THREAD

**Issue by Alchemi1** [Twisted-Fields/acorn-precision-farming-rover#23]
So it seems im getting a Temp failure resolving issue/error pulling down ubuntu repos when running the simulation.sh file when trying to fire up the docker. 
It seems its failing right after step 2/14. 
Any ideas? 

Thanks in advance! 
Love this project! So grateful for your work! Stellar

**Comment by tlalexander** [comment]
Hello and thank you for the comment! This is interesting as I was getting this too, but we recently got Starlink at the farm so brief disconnections are sometimes expected. In my case running it again allowed it to go through. But now you have me wondering if there is something wrong with the dockerfile. What happens if you try to run it multiple times? It always fails?

**Comment by Alchemi1** [comment]
Yes i ran it 4 times and same results. 
I can give it a try again on a different box and see if same results.  And if that doesnt work ill try to connect direct to main router.  Ill report back.
Thanks

**Comment by tlalexander** [comment]
Also possibly turning off VPN was another suggestion, I just tried a clean docker build and got the name resolution error. I ran sudo service docker restart and disconnected from VPN (I should have tried them one at a time oops) and then the build worked.

For testing you can force a clean docker build with:
`docker-compose -f docker-compose-simulation.yml build --no-cache`

Which is helpful for debugging the name resolution issue.

**Comment by merlinran** [comment]
Interesting that both of you hit the problem. When you see the error again, it may be useful to check the result of `dig <failed-server>` from both your OS and within a container a few times, for example, `docker run -ti ros:galactic-ros-core-focal dig <failed-server>` , to know if it's actually some DNS issue or something on Docker side.

**Comment by tlalexander** [comment]
I think this one has resolved itself.
