### ISSUE TITLE
&& python3 /install/bringup/ODriveAcorn/tools/fibre/python/setup.py install' returned a non-zero code: 2

### ISSUE THREAD

**Issue by samuk** [Twisted-Fields/acorn-precision-farming-rover#29]
Docker would only run as root, is that the problem here?

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 087b8b36bcc1
 ---> 00371d17bcd6
Step 13/18 : COPY bringup/ODriveAcorn /install/bringup/ODriveAcorn
 ---> 76ff29e0a506
Step 14/18 : RUN cd /install/bringup/ODriveAcorn/tools/ && python3 /install/bringup/ODriveAcorn/tools/fibre/python/setup.py install
 ---> Running in b115c61e0bd4
/bin/sh: 1: cd: can't cd to /install/bringup/ODriveAcorn/tools/
ERROR: Service 'acorn_vehicle' failed to build: The command '/bin/sh -c cd /install/bringup/ODriveAcorn/tools/ && python3 /install/bringup/ODriveAcorn/tools/fibre/python/setup.py install' returned a non-zero code: 2

**Comment by samuk** [comment]
sam@Thinkpad:~/acorn-precision-farming-rover$ sudo ./run_docker_simulation.sh

Step 14/18 : RUN cd /install/bringup/ODriveAcorn/tools/ && python3 /install/bringup/ODriveAcorn/tools/fibre/python/setup.py install
 ---> Running in 0e2f9c7322f8
/bin/sh: 1: cd: can't cd to /install/bringup/ODriveAcorn/tools/
ERROR: Service 'acorn_vehicle' failed to build: The command '/bin/sh -c cd /install/bringup/ODriveAcorn/tools/ && python3 /install/bringup/ODriveAcorn/tools/fibre/python/setup.py install' returned a non-zero code: 2

**Comment by merlinran** [comment]
The errors you saw were from building the docker image, and the root cause is `can't cd to /install/bringup/ODriveAcorn/tools/`. I didn't see anything under the `bringup/ODriveAcorn` so the error is not surprising. @tlalexander maybe forgot to add the relevant files to the repo?

**Comment by tlalexander** [comment]
Oh yeah that is strange, it looks like I forgot to add the files. I was doing a lot of wild hacking over the summer, which never got nailed down completely, and sometimes I don't like to check in messy stuff.

But we just got the new PCBs yesterday and we will no longer be using odrive. There's going to be a lot of changes to the code repo over the next couple of months, and I will make sure to check things in as soon as I can. Once I get basic functionality with the new system I am also going to work on a lot of clean up and documentation for all our resources.

@samuk what is your goal right now? to run simulation? I can make sure to un-break whatever it is you are working on.

**Comment by samuk** [comment]
I was just wanting to understand the system/ run the sim. Interested in whether I could integrate some visual navigation: https://github.com/Agroecology-Lab/visual-multi-crop-row-navigation/tree/ROS2

**Comment by tlalexander** [comment]
Checking up on old issues here. Odrive is deprecated in our repo and references to it will soon be removed, so I will close this.
Regarding ROS integration, we have once again discussed how our system architecture and ROS should be integrated and I foresee more work on that over the next year, so as we move towards release it will be clearer how to integrate ROS components.
