### ISSUE TITLE
Project Status ?

### ISSUE THREAD

**Issue by vkuehn** [Twisted-Fields/acorn-precision-farming-rover#31]
Can you kindly just give a note if you plan to be active again and work on the issues and pull requests ?

**Comment by tlalexander** [comment]
Hello! Yes the project is still under active development. I went through a major refactor to integrate the new motor controllers and in doing so I fell behind on git commits for several months. I've just committed the latest changes and I will work on removing old code files and general clean up. Thanks for the reminder about pull requests. I've just accepted the latest PR. Older PRs may be out of date, I will review them some other time.
